### ISSUE TITLE
Multiple test case failures produced

### ISSUE THREAD

**Issue by pete-woods** [mglaman/phpstan-junit#2]
When `drupal-check` uses this library via PHPStan, the XML output for errors incorrectly groups multiple `failure` tags as children of a single `testcase` tag.

This does not follow the Junit [XSD](https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/resources/jenkins-junit.xsd), where only a single failure is allowed per `testcase`.

In addition, the `failures` and `errors` attributes are only valid for `testsuite`, and not `testcase`.

i.e.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
   <testsuite name="PHPStan" failures="1">
      <testcase name="src/Foo.php" failures="2" errors="0" tests="9">
         <failure type="error" message="error on line 38" />
         <failure type="error" message="\another error on line 40" />
      </testcase>
   </testsuite>
</testsuites>
```

should be:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
   <testsuite name="PHPStan" failures="1" errors="0">
      <testcase name="src/Foo.php" classname="src/Foo" time="0.185">
         <failure type="error">error on line 38</failure>
      </testcase>
      <testcase name="src/Foo.php" classname="src/Foo" time="0.185">
         <failure type="error">another error on line 40</failure>
      </testcase>
   </testsuite>
</testsuites>
```

**Comment by wilsona** [comment]
The `xsd` you link to doesn't seem to prohibit more than one `failure` in a `testcase`. [Note the](https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/resources/jenkins-junit.xsd#L69) `maxOccurs="unbounded"`. The application I'm dealing with agrees with you, though; it chokes if there's more than one `failure` on a `testcase`.

A few attributes are also in the wrong place. 
1. The `tests` attribute on `testsuite` element is [required](https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/resources/jenkins-junit.xsd#L90), but missing.
2. The `failures`, `errors`, and `tests` attributes are illegal on `testcase`.

**Comment by wilsona** [comment]
It's worth noting that, though the patch produces valid output, it isn't *correct* output. It doesn't report `tests` or `errors` correctly. Fixing that would require digging into phpstan, which I'm not going to do. mglaman didn't either - the patch leaves his decision in place, report `0` `errors` and a number of `tests` equal to the number of `failures`.
